name: Deploy on push to main

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: Set up Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Webpack âš™ï¸
        run: cd _src && rm -rf node_modules && npm install && npm run build --if-present
        env:
          CI: true
      - name: Build âš™ï¸
        run: bash _src/_compile.sh
        env:
          CI: true
      - uses: JamesIves/github-pages-deploy-action@v4
        name: Deploy ğŸš€
        with:
          folder: build
          git-config-name: Automated
          git-config-email: hello@codeforsacramento.org
          branch: gh-pages
